[tool.poetry]
name = "private+public-key"
version = "0.1.0"
description = ""
authors = ["Rudi Farkas <rudi.farkas@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
